run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam
    - gosec
    - copyloopvar
    - nilerr
    - noctx
    - makezero
    - goconst

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - shadow

  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

  gosec:
    severity: medium
    confidence: medium

  gocritic:
    disabled-checks:
      - ifElseChain
      - elseif

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go$
      linters:
        - gosec
        - goconst
        - errcheck
        - govet
        - unparam
    # Allow intentional empty error handling branches
    - text: "SA9003: empty branch"
      linters:
        - staticcheck
    # Allow field alignment warnings
    - text: "fieldalignment:"
      linters:
        - govet
    # Allow unparam warnings
    - text: "is unused"
      linters:
        - unparam
    # Allow gitlab deprecated API (no alternative available yet)
    - text: "SA1019.*gitlab"
      linters:
        - staticcheck
