version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - copyloopvar
    - goconst
    - gocritic
    - gosec
    - makezero
    - misspell
    - nilerr
    - noctx
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-checks:
        - appendCombine
        - emptyFallthrough
        - equalFold
        - indexAlloc
        - initClause
        - methodExprCall
        - nestingReduce
        - ptrToRefParam
        - rangeExprCopy
        - rangeValCopy
        - stringXbytes
        - typeAssertChain
      disabled-checks:
        - ifElseChain  # False positives: checks different variables, bitwise flags, complex conditions
    gosec:
      severity: medium
      confidence: medium
    govet:
      disable:
        - shadow
        - fieldalignment  # Disabled: struct field ordering is micro-optimization
      enable-all: true
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Exclude some linters from running on test files
      - linters:
          - errcheck
          - goconst
          - gosec
          - govet  # Excludes fieldalignment from test files
        path: _test\.go$
      # Exclude deprecation warnings for gitlab client (library migration requires separate task)
      - linters:
          - staticcheck
        path: internal/gitlab/client\.go$
        text: SA1019.*gitlab\.Client.*deprecated
      - linters:
          - staticcheck
        path: internal/gitlab/client\.go$
        text: SA1019.*gitlab\.NewClient.*deprecated
      # Exclude var-naming false positive for standard 'types' package name
      - linters:
          - revive
        path: internal/types/project_test\.go$
        text: var-naming.*avoid meaningless package names
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
