---
version: 2
project_name: glf

before:
  hooks:
    - go mod download

builds:
  - id: glf
    main: ./cmd/glf
    binary: glf
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - loong64
      - ppc64le
      - s390x
    goarm:
      - "5"
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.buildTime={{ .Date }}"
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - id: glf
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: igusev
    name: glf
  prerelease: auto
  name_template: '{{ .Version }}'

snapshot:
  version_template: "{{ .Version }}-next"

brews:
  - repository:
      owner: igusev
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: "https://github.com/igusev/glf"
    description: "Fast CLI tool for instant fuzzy search across self-hosted GitLab projects"
    license: "MIT"
    test: |
      system "#{bin}/glf", "--help"
    install: |
      bin.install "glf"

scoops:
  - repository:
      owner: igusev
      name: scoop-bucket
      branch: main
    directory: bucket
    homepage: "https://github.com/igusev/glf"
    description: "Fast CLI tool for instant fuzzy search across self-hosted GitLab projects"
    license: "MIT"

nfpms:
  - id: glf
    package_name: glf
    vendor: Igor Gusev
    homepage: "https://github.com/igusev/glf"
    maintainer: "Igor Gusev <igusev@example.com>"
    description: "Fast CLI tool for instant fuzzy search across self-hosted GitLab projects"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/glf/LICENSE
      - src: README.md
        dst: /usr/share/doc/glf/README.md

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
      - 'README'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Others
      order: 999
