name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the following information.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Brief description of the bug
      placeholder: Describe the issue you encountered
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Search for '...'
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: GLF Version
      description: Run `glf --version`
      placeholder: "v0.3.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your OS and version
      placeholder: "macOS 14.0, Ubuntu 22.04, Windows 11, etc."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output (optional)
      description: Paste any error messages or run with `glf --verbose`
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (optional)
      description: Screenshots, workarounds, or other relevant information
    validations:
      required: false
