name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you need.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem or limitation you're facing
      placeholder: I need to... but currently GLF doesn't...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe your ideal solution
      placeholder: It would be great if GLF could...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: How would you use it?
      description: Describe your specific use case
      placeholder: In my workflow, I would...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (optional)
      description: Examples, screenshots, or links to similar features
    validations:
      required: false
